server:
  port: 8001
spring:
  application:
    name: provide-nacos-service #注册到注册中心的名字  提供者
  cloud:
    nacos:
      discovery:
        server-addr: 8.129.51.229:8848 #nacos的ip地址
  #redis集成权限sa-token
  # redis配置
  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: 8.129.51.229
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: Lt200804
    # 连接超时时间（毫秒）
    timeout: 10s
    jedis:
#    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 300ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
  # sa-token配置
  sa-token:
    # token名称 (同时也是cookie名称)
    token-name: satoken
    # token有效期，单位s 默认15,30天, -1代表永不过期
    timeout: 1296000 #2592000
    # token临时有效期 (指定时间内无操作就视为token过期) 单位: 900秒，15分钟
    activity-timeout: 900 #-1
    # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
    allow-concurrent-login: false
    # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
    is-share: false
    # token风格
    token-style: uuid
    #jdbc配置
  #数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.129.51.229/k?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&useTimezone=true&serverTimezone=GMT%2B8&useLegacyDatetimeCode=false #jdbc:mysql://8.129.51.229/k?useunicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true
    username: k
    password: longtao
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
  servlet:
    multipart:
      max-file-size: 1050MB
      max-request-size: 1050MB
    #数据库框架
mybatis-plus:
  mapper-locations: classpath:Mapper/*.xml  #mybatis指定数据库xml文件
  typeAliasesPackage: com.lt.Entity      #指定实体类
  configuration:
    map-underscore-to-camel-case: false  #关闭驼峰，实体类的 *_*映射
    auto-mapping-behavior: full
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 0
      logic-not-delete-value: 1
  #http://ip地址:17790/doc.html
knife4j:
  # 开启增强配置
  enable: true
  setting:
    # Knife4j默认显示中文(zh-CN),如果开发者想直接显示英文(en-US)，在通过该配置进行设置即可
    language: en-US
    # 对于调试中的请求参数是否缓存进行开启配置，该参数默认为true
    enableRequestCache: true
  # 开启Swagger的Basic认证功能,默认是false
  basic:
    enable: true
    # Basic认证用户名
    username: boran
    # Basic认证密码
    password: boran123
###producer
#rocketmq:
#  name-server: 8.129.51.229:9876
##  生产者
#  producer:
#    group: my-group-lt


